"""Optimization API Pydantic schemas (Batch 6B.3).

Schemas for optimization runs, trigger requests, and optimized blocks.
All models explicitly distinguish computational recommendations from
human-approved railway blocks.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from app.models.negotiation import NegotiationAction, AdjustmentCategory


class OptimizationRunCreateRequest(BaseModel):
    """Request payload to trigger a new CP-SAT optimization run."""

    planning_start: datetime | None = Field(
        None,
        description="Start timestamp of the optimization horizon (UTC). If null, covers earliest candidate window.",
    )
    planning_end: datetime | None = Field(
        None,
        description="End timestamp of the optimization horizon (UTC). If null, covers latest candidate window.",
    )

    @field_validator("planning_start", "planning_end", mode="after")
    @classmethod
    def ensure_utc_timestamps(cls, v: datetime | None) -> datetime | None:
        if v is not None and v.tzinfo is None:
            return v.replace(tzinfo=timezone.utc)
        return v
    run_type: str = Field(
        default="standard",
        max_length=50,
        description="Identifier tag for the run (e.g. 'standard', 'weekly', 'scenario_a').",
    )
    solver_time_limit_seconds: float = Field(
        default=10.0,
        ge=1.0,
        le=60.0,
        description="Maximum solver runtime in seconds (1.0 to 60.0).",
    )
    allow_train_conflicts: bool = Field(
        default=False,
        description="If True, permits candidate blocks that have train schedule conflicts.",
    )
    require_resource_feasibility: bool = Field(
        default=False,
        description="If True, prunes candidate blocks whose depot resources are unverified.",
    )
    max_block_duration_hrs: float = Field(
        default=8.0,
        ge=1.0,
        le=24.0,
        description="Maximum allowed possession duration per block (hours).",
    )

    # Optional objective weight overrides
    weight_priority_score: float | None = Field(
        None, ge=0.0, le=10.0, description="Override weight for delivered priority."
    )
    weight_integrated_task_bonus: float | None = Field(
        None, ge=0.0, le=10.0, description="Override weight for multi-task synergy."
    )
    weight_tasks_scheduled: float | None = Field(
        None, ge=0.0, le=10.0, description="Override weight for total tasks scheduled."
    )
    weight_overdue_mitigation: float | None = Field(
        None, ge=0.0, le=10.0, description="Override weight for overdue backlog mitigation."
    )
    weight_train_disruption: float | None = Field(
        None, ge=0.0, le=10.0, description="Override penalty weight for train conflicts."
    )
    weight_freight_impact: float | None = Field(
        None, ge=0.0, le=10.0, description="Override penalty weight for freight impact."
    )
    weight_unused_window_time: float | None = Field(
        None, ge=0.0, le=10.0, description="Override penalty weight for unused window hours."
    )
    weight_total_block_count: float | None = Field(
        None, ge=0.0, le=10.0, description="Override penalty weight for total block count."
    )


class OptimizedBlockResponse(BaseModel):
    """Recommended maintenance block generated by the optimizer."""

    model_config = ConfigDict(from_attributes=True)

    id: int = Field(..., description="Database ID of the optimized block")
    optimization_run_id: int = Field(..., description="ID of the parent optimization run")
    optimized_block_id: str = Field(..., description="Unique generated block identifier")
    candidate_id: str | None = Field(None, description="Source candidate block ID")
    section_id: str = Field(..., description="Railway section ID")
    block_start: datetime = Field(..., description="Scheduled possession start time (UTC)")
    block_end: datetime = Field(..., description="Scheduled possession end time (UTC)")
    block_duration_hrs: float = Field(..., description="Duration of maintenance block in hours")
    block_type: str = Field(..., description="'single' or 'integrated'")
    is_integrated: bool = Field(..., description="True if block consolidates multiple departments/tasks")
    departments_involved: list[str] = Field(..., description="List of participating departments")
    realized_priority_value: float = Field(
        ...,
        description="Authentic summed priority of scheduled tasks driving the optimization decision.",
    )
    candidate_priority_value: float | None = Field(
        None,
        description="Initial heuristic priority score computed during candidate generation stage.",
    )
    train_conflicts: int = Field(0, description="Number of train timetable conflicts")
    estimated_impact_score: float | None = Field(None, description="Task compatibility score")
    resource_status: str | None = Field("UNVERIFIED", description="Resource verification status")
    freight_impact: str | None = Field(None, description="Freight traffic impact level")
    task_ids: list[str] = Field(default_factory=list, description="IDs of maintenance tasks scheduled in this block")
    status: str = Field(
        "Candidate",
        description="Operational status ('Candidate', 'Approved', 'Rejected'). Defaults to Candidate recommendation.",
    )
    explanation: dict[str, Any] | None = Field(None, description="Structured rationale and constraint data")
    created_at: datetime | None = Field(None, description="Creation timestamp")


class NegotiationRequest(BaseModel):
    """Payload for a department to negotiate a block recommendation."""

    department: str = Field(..., description="Department name (e.g., ENGINEERING, SNT, TRD)")
    action: NegotiationAction = Field(..., description="One of 'ACCEPT', 'ADJUST', 'REJECT'")
    comment: str | None = Field(None, description="Optional comment or reason for the action")
    adjustment_category: AdjustmentCategory | None = Field(
        None, description="Category for adjustment if action is ADJUST"
    )
    adjustment_payload: dict[str, Any] | None = Field(
        None, description="Adjustment details payload with value and reason"
    )

    @field_validator("department", mode="after")
    @classmethod
    def validate_department(cls, v: str) -> str:
        dept = v.strip().upper()
        if dept in ("ENGINEERING", "ENGG"):
            return "ENGINEERING"
        if dept in ("SNT", "S&T", "S_AND_T", "SIGNAL"):
            return "SNT"
        if dept in ("TRD", "TRACTION"):
            return "TRD"
        return dept

    @model_validator(mode="after")
    def validate_adjust_payload(self) -> NegotiationRequest:
        if self.action == NegotiationAction.ADJUST:
            if not self.adjustment_category:
                raise ValueError("adjustment_category must be provided for ADJUST action")
            if not isinstance(self.adjustment_payload, dict):
                raise ValueError("adjustment_payload must be a dict for ADJUST action")
            if set(self.adjustment_payload.keys()) != {"value", "reason"}:
                raise ValueError('adjustment_payload must contain exactly keys "value" and "reason"')
            if not isinstance(self.adjustment_payload.get("value"), str) or not isinstance(self.adjustment_payload.get("reason"), str):
                raise ValueError("adjustment_payload fields must be strings")
            if not self.adjustment_payload.get("value", "").strip() or not self.adjustment_payload.get("reason", "").strip():
                raise ValueError("adjustment_payload value and reason cannot be empty")
        return self


class NegotiationResponse(BaseModel):
    """Response after a negotiation action is recorded."""

    model_config = ConfigDict(from_attributes=True)

    id: int = Field(..., description="Database ID of the negotiation record")
    optimized_block_id: int = Field(..., description="ID of the block being negotiated")
    department: str = Field(..., description="Department that performed the action")
    action: NegotiationAction = Field(..., description="Action taken: ACCEPT, ADJUST, REJECT")
    comment: str | None = Field(None, description="Optional comment")
    adjustment_category: AdjustmentCategory | None = Field(None, description="Adjustment category if applicable")
    adjustment_payload: dict[str, Any] | None = Field(None, description="Adjustment details payload")
    performed_by: str = Field(..., description="Username of the user who performed the action")
    timestamp: datetime = Field(..., description="When the action was recorded")


class OptimizationRunResponse(BaseModel):
    """Metadata and summary results of an optimization run."""

    model_config = ConfigDict(from_attributes=True)

    id: int = Field(..., description="Database primary key ID")
    run_id: str = Field(..., description="Domain run identifier (e.g. 'RUN-E1A76690')")
    run_type: str | None = Field("standard", description="Run classification tag")
    planning_horizon_start: datetime | None = Field(None, description="Planning window start (UTC)")
    planning_horizon_end: datetime | None = Field(None, description="Planning window end (UTC)")
    status: str = Field(..., description="Execution status ('Completed', 'Failed')")
    solver_status: str = Field(..., description="CP-SAT status ('OPTIMAL', 'FEASIBLE', 'INFEASIBLE')")
    objective_value: float | None = Field(None, description="Composite mathematical objective value")
    solve_time_seconds: float | None = Field(None, description="Solver execution time in seconds")
    tasks_considered: int = Field(0, description="Total active maintenance tasks considered")
    tasks_scheduled: int = Field(0, description="Number of maintenance tasks successfully scheduled")
    tasks_unassigned: int = Field(0, description="Number of maintenance tasks unassigned due to constraints")
    integrated_block_count: int = Field(0, description="Number of multi-task integrated blocks scheduled")
    separate_block_count: int = Field(0, description="Number of single-task blocks scheduled")
    estimated_total_block_hours: float = Field(0.0, description="Total possession hours across all scheduled blocks")
    unassigned_task_ids: list[str] = Field(default_factory=list, description="List of unassigned task IDs")
    warnings: list[str] = Field(default_factory=list, description="Warnings and constraint pruning logs")
    # Human Approval Workflow (Batch 7J)
    approval_status: str = Field(
        "DRAFT",
        description="Human business approval state ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED')",
    )
    submitted_by: str | None = Field(None, description="Username of the planner who submitted for review")
    submitted_at: datetime | None = Field(None, description="Timestamp when submitted for review")
    approved_by: str | None = Field(None, description="Username of the authority who approved the plan")
    approved_at: datetime | None = Field(None, description="Timestamp when approved")
    rejected_by: str | None = Field(None, description="Username of the authority who rejected the plan")
    rejected_at: datetime | None = Field(None, description="Timestamp when rejected")
    rejection_reason: str | None = Field(None, description="Detailed explanation for rejection")
    created_at: datetime | None = Field(None, description="Timestamp when run was executed")


class OptimizationRejectRequest(BaseModel):
    """Payload to reject an optimization run submitted for approval."""

    reason: str = Field(
        ...,
        min_length=5,
        max_length=1000,
        description="Mandatory meaningful explanation for rejecting the proposed plan (min 5 characters).",
    )


class OptimizationRunDetailResponse(OptimizationRunResponse):
    """Detailed optimization run with all nested scheduled blocks."""

    scheduled_blocks: list[OptimizedBlockResponse] = Field(
        default_factory=list, description="List of scheduled maintenance blocks"
    )


class OptimizedBlocksListResponse(BaseModel):
    """Paginated list of optimized maintenance blocks."""

    items: list[OptimizedBlockResponse]
    total: int
    page: int
    page_size: int
    total_pages: int


class OptimizationRunsListResponse(BaseModel):
    """Paginated list of historical optimization runs."""

    items: list[OptimizationRunResponse]
    total: int
    page: int
    page_size: int
    total_pages: int


class DepartmentMessageCreateRequest(BaseModel):
    """Request payload to post a message in the department communication channel."""

    department: str = Field(..., description="Department sending the message (ENGINEERING, SNT, TRD)")
    message: str = Field(..., min_length=1, max_length=2000, description="Message text")
    message_type: str | None = Field("CHAT", description="Type: CHAT, PROPOSAL, OBJECTION, CLARIFICATION")

    @field_validator("department")
    @classmethod
    def validate_department(cls, v: str) -> str:
        dept = v.strip().upper()
        if dept in ("ENGINEERING", "ENGG"):
            return "ENGINEERING"
        if dept in ("SNT", "S&T", "S_AND_T", "SIGNAL"):
            return "SNT"
        if dept in ("TRD", "TRACTION"):
            return "TRD"
        return dept


class DepartmentMessageResponse(BaseModel):
    """Response schema for an inter-department communication message."""

    model_config = ConfigDict(from_attributes=True)

    id: int = Field(..., description="Message ID")
    optimized_block_id: int = Field(..., description="Optimized block ID")
    department: str = Field(..., description="Department label")
    actor: str = Field(..., description="Username / actor who posted the message")
    message: str = Field(..., description="Message body")
    message_type: str | None = Field("CHAT", description="Message category")
    timestamp: datetime = Field(..., description="UTC timestamp of the message")
